version: "3.8"

services:
  mf_video:
    build:
      dockerfile: Dockerfile
    container_name: mf_video
    ports:
      - "8013:8013"
    restart: always
    volumes:
      - ./cache:/mf-video/cache
      - ./data://mf-video/data
      - mf_video_shared:/app/mf-video
    environment:
      - DATA_DIR=${DATA_DIR}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DB=${DB_DB}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    depends_on:
      - mf_video_db
    networks:
      - mf_video_network
    env_file:
      - .env

  mf_video_db:
    image: postgres:latest
    container_name: mf_video_db
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_DB}
      - TZ=Europe/Warsaw
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mf_video_network
    env_file:
      - .env

volumes:
  postgres_data:
  mf_video_shared:

networks:
  mf_video_network:
    driver: bridge
